export type WorldLink = {
  href: string;
  title: string;
  body: string;
  kind?: "markdown" | "image" | "timeline";
  section?: string;
  story?: boolean;
  private?: boolean;
};

export const worldLinks: WorldLink[] = [
  {
    href: "./world/docs/overview-disciple.md",
    title: "제자의 기록",
    body: "괴력난신 세계의 첫 기록",
    section: "세계서",
    story: true,
  },
  {
    href: "./world/docs/overview-land.md",
    title: "땅의 형성",
    body: "잘려 나온 대륙의 기록",
    section: "세계서",
    story: true,
  },
  {
    href: "./world/docs/overview-powers-rise.md",
    title: "기이열국의 발흥",
    body: "새로운 열국의 등장",
    section: "세계서",
    story: true,
  },
  {
    href: "./world/docs/overview-goblin-song.md",
    title: "도깨비 문지기 노래",
    body: "문 앞에서 주워 온 노래",
    section: "세계서",
    story: true,
  },
  {
    href: "./world/docs/factions.md",
    title: "열국",
    body: "예맥, 사로국, 가락, 십제, 중립",
    section: "세계서",
    story: true,
  },
  {
    href: "./world/maps/map-2026-05-30.svg",
    title: "지도",
    body: "지도",
    kind: "image",
  },
  {
    href: "./world/fiction/prologue.md",
    title: "대변혁 이후",
    body: "서장",
    section: "세계서",
    story: true,
  },
  {
    href: "./world/docs/expansion-01.md",
    title: "드러나는 이면",
    body: "첫 확장팩 배경 문서",
    section: "세계서",
    story: true,
  },
  {
    href: "./world/stories/first-gate/beom.md",
    title: "범",
    body: "첫성문 · 산과 발톱",
    section: "첫성문",
    story: true,
  },
  {
    href: "./world/stories/first-gate/fox.md",
    title: "여우",
    body: "첫성문 · 소문과 계략",
    section: "첫성문",
    story: true,
  },
  {
    href: "./world/stories/first-gate/wolf.md",
    title: "이리",
    body: "첫성문 · 굶주림과 군율",
    section: "첫성문",
    story: true,
  },
  {
    href: "./world/stories/first-gate/cat.md",
    title: "고양이",
    body: "첫성문 · 밤과 기다림",
    section: "첫성문",
    story: true,
  },
  {
    href: "./world/stories/first-gate/bear.md",
    title: "곰",
    body: "첫성문 · 침묵과 각성",
    section: "첫성문",
    story: true,
  },
  {
    href: "./world/stories/base/yemaek.md",
    title: "예맥",
    body: "기본/확장 · 용력과 원혼",
    section: "열국",
    story: true,
  },
  {
    href: "./world/stories/base/sipje.md",
    title: "십제",
    body: "기본/확장 · 제사와 귀신",
    section: "열국",
    story: true,
  },
  {
    href: "./world/stories/base/garak.md",
    title: "가락",
    body: "기본/확장 · 반란과 알",
    section: "열국",
    story: true,
  },
  {
    href: "./world/stories/base/saro.md",
    title: "사로국",
    body: "기본/확장 · 도깨비와 왕좌",
    section: "열국",
    story: true,
  },
  {
    href: "./world/stories/expansions/bulnaeye.md",
    title: "불내예",
    body: "중립 확장 · 치욕과 소문",
    section: "확장",
    story: true,
    private: true,
  },
  {
    href: "./world/stories/expansions/hudorgi.md",
    title: "후도르기",
    body: "이후 확장 · 제국과 조서",
    section: "확장",
    story: true,
    private: true,
  },
  {
    href: "./world/stories/expansions/yo-ma.md",
    title: "요와 마",
    body: "이후 확장 · 이름 붙인 괴물",
    section: "확장",
    story: true,
    private: true,
  },
  {
    href: "./world/stories/expansions/imae-mangryang.md",
    title: "이매와 망량",
    body: "이후 확장 · 얼굴 없는 세력",
    section: "확장",
    story: true,
    private: true,
  },
  {
    href: "./world/stories/expansions/yayoi.md",
    title: "야요이",
    body: "이후 확장 · 바다 건너 의식",
    section: "확장",
    story: true,
    private: true,
  },
  {
    href: "./world/stories/expansions/parthia-kushan.md",
    title: "파르티아와 쿠샨",
    body: "이후 확장 · 서쪽 길",
    section: "확장",
    story: true,
    private: true,
  },
  {
    href: "./world/stories/expansions/cheonchuk-dapana.md",
    title: "천축국과 다파나",
    body: "이후 확장 · 바깥의 기원",
    section: "확장",
    story: true,
    private: true,
  },
  {
    href: "./world/stories/expansions/romania.md",
    title: "로마니아",
    body: "이후 확장 · 먼 서쪽의 제국",
    section: "확장",
    story: true,
    private: true,
  },
];
